apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workloads-logging
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/jswamina-redhat/logging-apps-test.git
        revision: main
        directories:
          - path: workloads-logging/*
  template:
    metadata:
      name: "{{ .path.basename }}"
      namespace: openshift-gitops
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/jswamina-redhat/logging-apps-test.git
        targetRevision: main
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .path.basename }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 10
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m