apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: log-to-loki
  namespace: openshift-logging
spec:
  serviceAccount:
    name: tt-log-forwarder
  outputs:
    - name: external-loki
      type: loki
      loki:
        url: 'https://logs-prod-021.grafana.net' # TT LOKI: 'https://logs-prod-006.grafana.net' # base URL; collector appends /loki/api/v1/push
        # secret:
        #   name: tt-loki-auth # Created / rotated by ESO
        labelKeys:
          - log_type
          - kubernetes.namespace_name
          - openshift.cluster_id
        authentication:
          username:
            secretName: tt-loki-auth
            key: username
          password:
            secretName: tt-loki-auth
            key: password
  pipelines:
    - name: all-to-loki
      inputRefs:
        - application
        - infrastructure
        - audit
      outputRefs:
        - external-loki