apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-credentials-es
  namespace: openshift-logging
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: tt-aws-secret-store
    kind: SecretStore
  target:
    name: tt-loki-auth
    creationPolicy: Owner
  data:
    - secretKey: "" # TODO: Get from TT AWS Secret Manager
      remoteRef:
        key: "" # TODO: Get from TT AWS Secret Manager
        property: "" # TODO: Key inside AWS secrets manager 