apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-credentials-es
  namespace: openshift-logging
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: tt-aws-secret-store # TODO: Name of the cluster secret store
    kind: ClusterSecretStore
  target:
    name: tt-loki-auth
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: sre/grafana/alloy_stage